# Generated by Django 5.0.6 on 2024-06-23 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=255)),
                ('asientos', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/usuarios', verbose_name='Imagen')),
                ('dni', models.CharField(help_text='Documento Nacional de Identidad', max_length=50, unique=True, verbose_name='DNI')),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('estado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.categoria', verbose_name='Categoría')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario relacionado')),
            ],
            options={
                'verbose_name_plural': 'Personas',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=150, verbose_name='Cliente')),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('boleto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.persona', verbose_name='Persona relacionada')),
            ],
            options={
                'verbose_name_plural': 'Registros',
                'ordering': ['fecha'],
            },
        ),
    ]
