# Generated by Django 5.0.6 on 2024-06-25 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ventaboletos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=150, verbose_name='Cliente')),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('boleto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asiento', models.PositiveIntegerField(verbose_name='Número de Asiento')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.persona', verbose_name='Persona relacionada')),
            ],
            options={
                'verbose_name_plural': 'Registros',
                'ordering': ['fecha'],
                'unique_together': {('persona', 'asiento')},
            },
        ),
    ]
