# Generated by Django 5.0.6 on 2024-06-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0003_turno_persona_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='turno',
        ),
    ]
