# Generated by Django 5.0.6 on 2024-06-25 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0004_remove_persona_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.persona', verbose_name='Persona relacionada')),
            ],
        ),
    ]
